skip-check:
  - id: CKV_AWS_2
    ressource: aws_lb_listener.http
    comment: "HTTP listener uniquement pour redirect->HTTPS"
  - id: CKV_AWS_111
    resource: aws_iam_policy_document.deploy_min
    comment: "Déploiement ECS/ALB autoscaling: actions d'écriture sans ARN scoping pratique."
  - id: CKV_AWS_356
    resource: aws_iam_policy_document.deploy_min
    comment: "Describe*/List*/PutMetricAlarm/CreateServiceLinkedRole exigent Resource='*' côté IAM."
