name: Trivy Scan

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Nécessaire pour uploader le SARIF dans l'onglet Security
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image (local tag)
        run: docker build -t fastapi-template:ci .

      # Installe la CLI Trivy (version stable)
      - name: Setup Trivy CLI
        uses: aquasecurity/setup-trivy@v0.2.3

      # Affiche un résumé dans les logs (n'échoue pas le job pour l'instant)
      - name: Trivy (summary in logs)
        run: |
          trivy image \
            --ignore-unfixed \
            --severity CRITICAL,HIGH,MEDIUM \
            --format table \
            fastapi-template:ci

      # Télécharge le template HTML officiel de Trivy
      - name: Fetch Trivy HTML template
        run: |
          curl -sSLo trivy-html.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      # Génére le rapport HTML
      - name: Generate Trivy HTML report
        run: |
          trivy image \
            --ignore-unfixed \
            --severity CRITICAL,HIGH,MEDIUM \
            --format template \
            --template "@trivy-html.tpl" \
            -o trivy-report.html \
            fastapi-template:ci

      # Génére le rapport SARIF (pour l’onglet Security)
      - name: Generate Trivy SARIF report
        run: |
          trivy image \
            --ignore-unfixed \
            --severity CRITICAL,HIGH,MEDIUM \
            --format sarif \
            -o trivy-report.sarif \
            fastapi-template:ci

      # Upload l’HTML comme artifact téléchargeable
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-html
          path: trivy-report.html
          retention-days: 7

      # Envoie le SARIF dans Security → Code scanning alerts
      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif
