name: app-ci

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'app/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'app/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (PR)
    environment: dev
    env:
        AWS_REGION: ${{ vars.AWS_REGION }}
        NAME_PREFIX: ${{ vars.NAME_PREFIX }}     # fastapi
        ENVIRONMENT:   ${{ vars.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt || true
      - name: Pytest
        env:
            PYTHONPATH: ${{ github.workspace }}
        run: pytest -q || true

  build_and_push:
    name: Build & Push ECR (main)
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev
    env:
        AWS_REGION: ${{ vars.AWS_REGION }}
        NAME_PREFIX: ${{ vars.NAME_PREFIX }}     # fastapi
        ENVIRONMENT:   ${{ vars.ENVIRONMENT }}
        ECR_REPO: ${{ vars.NAME_PREFIX }}-${{ vars.ENVIRONMENT }}-ecr
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false }

      - name: Configure AWS (OIDC) - build role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_BUILD_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Compute ECR repo URL & tag
        id: meta
        shell: bash
        run: |
          ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
          echo "repo_url=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_SHA::12}" >> $GITHUB_OUTPUT
          echo "Will push to: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${GITHUB_SHA::12}"

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest-${{ vars.ENVIRONMENT }}
