name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-lint:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff

    - name: Lint with Ruff
      run: |
        ruff check app tests --fix

    - name: Wait for MongoDB to be ready
      run: |
        echo "Waiting for MongoDB..."
        sleep 15

    - name: Run Pytest
      run: |
        PYTHONPATH=. pytest
