name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      MONGO_URL: mongodb://127.0.0.1:27017
      DATABASE_NAME: testdb_ci
      SECRET_KEY: testsecret_ci
    services:
      mongo:
        image: mongo:7.0
        ports: ['27017:27017']
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Mongo
        run: |
          for i in {1..60}; do
            echo "waiting for mongo..."
            nc -z 127.0.0.1 27017 && echo "mongo up" && break
            sleep 1
          done

      - name: Run unit tests
        run: pytest -m "not integration" -v

  integration-tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      MONGO_URL: mongodb://127.0.0.1:27017
      DATABASE_NAME: testdb_ci
      SECRET_KEY: testsecret_ci
    services:
      mongo:
        image: mongo:7.0
        ports: ['27017:27017']
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Mongo
        run: |
          for i in {1..60}; do
            echo "waiting for mongo..."
            nc -z 127.0.0.1 27017 && echo "mongo up" && break
            sleep 1
          done

      - name: Run integration tests
        run: pytest -m integration -v
