name: iac-security
on:
  pull_request:
    paths: ["infra/**", ".github/workflows/**"]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Run tfsec and emit SARIF
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: infra
          format: sarif
          soft_fail: true

      - name: Export SARIF
        run: tfsec infra --format sarif --out tfsec.sarif || true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif

      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra
          framework: terraform
          quiet: true
          soft_fail: false
