name: Trivy Scan

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write   # <- nécessaire pour upload SARIF
  actions: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image (local tag)
        run: docker build -t fastapi-template:ci .

      # Installe la CLI trivy pour les steps suivants
      - name: Setup Trivy CLI
        uses: aquasecurity/setup-trivy@v0

      # 1) Affichage rapide dans les logs (table)
      - name: Trivy (table in logs)
        run: |
          trivy image --ignore-unfixed --severity CRITICAL,HIGH,MEDIUM \
            --format table fastapi-template:ci

      # 2) Génère un rapport JSON pour artefact
      - name: Trivy JSON report
        run: |
          trivy image --ignore-unfixed --severity CRITICAL,HIGH,MEDIUM \
            --format json -o trivy-report.json fastapi-template:ci

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-json
          path: trivy-report.json
          retention-days: 7

      # 3) (Optionnel) Génère SARIF et pousse dans l'onglet Security
      - name: Trivy SARIF report
        run: |
          trivy image --ignore-unfixed --severity CRITICAL,HIGH,MEDIUM \
            --format sarif -o trivy-report.sarif fastapi-template:ci

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif
